#
# This file contains a list with different configurations for test cases which rely on store.
#
# Feel free to copy it to test-config.yml and adapt. You can reuse existing configurations or you can use your own.

arc2Config: &arc2Config
    username: "root"
    password: ""
    host: "127.0.0.1"
    database: "saft"
    table-prefix: "saft"
